version: "3"
services:
  mysql:
    image: mysql:8.0.28
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ../MySqlCopy:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Licenta123!
      MYSQL_DATABASE: cloudproject
  auth:
    depends_on:
      - mysql
    build: ./Auth
    ports:
      - "127.0.0.1:8070:8070"
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysql:3306/cloudproject",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "Licenta123!",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.generate-ddl":"true",
        "spring.jpa.properties.hibernate.format_sql":"true",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers":"true"
      }'
  order:
    depends_on:
      - mysql
    build: ./Order
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql:3306/cloudproject",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "Licenta123!",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.generate-ddl":"true",
        "spring.jpa.properties.hibernate.format_sql":"true",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers":"true"
      }'
  product:
    depends_on:
      - mysql
    build: ./Product
    ports:
      - "127.0.0.1:8090:8090"
    environment:
      SPRING_APPLICATION_JSON: '{
       "spring.datasource.url"  : "jdbc:mysql://mysql:3306/cloudproject",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "Licenta123!",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.jpa.generate-ddl":"true",
        "spring.jpa.properties.hibernate.format_sql":"true",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers":"true"
      }'
  angular:
      depends_on:
        - mysql
      build: ./Frontend
      ports:
        - "127.0.0.1:4200:4200"
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  load-balancer:
    build: ./nginx-config
    image: ./nginx-config/nginx
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:80:80"
    networks:
      - app_network

networks:
  app_network: